<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="559505" started-at="2020-01-22T18:02:42Z" finished-at="2020-01-22T18:12:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="559505" started-at="2020-01-22T18:02:42Z" finished-at="2020-01-22T18:12:01Z">
      <class name="com.hellofresh.challenge.WebTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="setup" is-config="true" duration-ms="90" started-at="2020-01-22T23:32:42Z" finished-at="2020-01-22T23:32:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="launchApplication" is-config="true" duration-ms="15128" started-at="2020-01-22T23:32:42Z" finished-at="2020-01-22T23:32:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="LogIntest()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="LogIntest" duration-ms="16083" started-at="2020-01-22T23:32:57Z" finished-at="2020-01-22T23:33:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LogIntest -->
        <test-method status="FAIL" signature="signInTest()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="signInTest" duration-ms="543434" started-at="2020-01-22T23:32:57Z" finished-at="2020-01-22T23:42:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hellofresh.challenge.SignUpPage.SignInSuccessAsserts(SignUpPage.java:93)
	at com.hellofresh.challenge.WebTest.signInTest(WebTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method status="FAIL" signature="CheckOuttest()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="CheckOuttest" duration-ms="54531" started-at="2020-01-22T23:33:13Z" depends-on-methods="com.hellofresh.challenge.WebTest.LogIntest" finished-at="2020-01-22T23:34:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [MY ACCOUNT] but found [WOMEN 
There are 7 products.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.hellofresh.challenge.CheckOutPage.checkoutTest(CheckOutPage.java:52)
	at com.hellofresh.challenge.WebTest.CheckOuttest(WebTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckOuttest -->
        <test-method status="PASS" signature="closeBroswer()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="closeBroswer" is-config="true" duration-ms="732" started-at="2020-01-22T23:42:00Z" finished-at="2020-01-22T23:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBroswer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hellofresh.challenge.WebTest@35083305]" name="tearDown" is-config="true" duration-ms="200" started-at="2020-01-22T23:42:01Z" finished-at="2020-01-22T23:42:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hellofresh.challenge.WebTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
